### ISSUE TITLE
Some elements are in wrong namespace

### ISSUE THREAD

**Issue by nigelmegitt** [bbc/ebu-tt-live-toolkit#2]
The `agent`, `title` and `desc` elements should be in the `ttm:` namespace but are in `ebuttm:`

The `copyright` element should be in the `ttm:` namespace but is in no namespace.

This doesn't seem to be an issue with attributes.

**Comment by kozmaz87** [comment]
That is caused by them being defined in the ebutt_metadata file that defines a targetNamespace. I can try to lift them out of there to the metadata file that has ttm as target namespace.

This is a restriction I cannot assign on the spot namespace to things defined in a file that defines targetNamespace
